Add compatibility with Symfony 6.0
gammadia/gammadia-translator pull request #1
Opened 2022-04-11 12:23 UTC by ZHB

`"phpmyadmin/motranslator": "dev-master"` will need to be modified with the corresponding tag when master is tagged

2022-04-11 12:38 UTC, gnutix requested changes

2022-04-11 12:38 UTC, gnutix commented on composer.json
> +        "phpmyadmin/motranslator": "dev-master"
A choix, peux-tu la figer au commit actuel de dev-master stp ?

2022-04-11 12:43 UTC, ZHB commented on composer.json
> +        "phpmyadmin/motranslator": "dev-master"
Effectivement, bonne idée.

2022-04-28 08:46 UTC, ZHB commented on composer.json
> +        "phpmyadmin/motranslator": "dev-master"
La lib est maintenant compatible avec Symfony 6.0

2022-04-28 08:47 UTC, gnutix approved these changes

2022-04-28 08:53 UTC, merged